{
 "title": "Kafka Order Platform",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Message Production Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(kafka_messages_produced_total[1m])",
     "legendFormat": "Produced: {{service}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Message Consumption Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(kafka_messages_consumed_total[1m])",
     "legendFormat": "Consumed: {{service}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Inflight Handlers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "inflight_handlers", "legendFormat": "{{service}} Inflight" }
   ]
  },
  {
   "title": "Handler Errors (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(handler_errors_total[1m])", "legendFormat": "{{service}} Errors" }
   ]
  }
 ]
}